### PR TITLE
add some xpad pids

### PR DESCRIPTION
**Pull request by zzattack**
Added the Razer Sabertooth controller to the xpad device list, and removed the patch that killed support for a Chinese no-name controller.

### CODE REVIEW

**Comment by garbear** [comment]
please separate

**Comment by garbear** [comment]
just re-discovered this. I'm working on a RetroPlayer buld with OpenELEC 6 and Kodi 15.1. should I include this patch?

**Comment by zzattack** [comment]
Nah, they're part of xpad in linux kernel by now.

**Comment by garbear** [comment]
nice. i'm hoping to release the openelec images today or tmrw

**Pull request closed without merging**
